version: '3.1'
services:
### NGINX #####################################
  nginx:
    build: ./nginx
    ports: 
      - 80:80
#      - 443:443
    restart: always
    volumes: 
      - ./nginx/:/etc/nginx/conf.d/
      - ./www/:/usr/share/nginx/html

### My SQL #####################################
  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: bbq
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    

### PHPMYADMIN #####################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  
