version: '3.1'
services:
### NGINX #####################################
  nginx:
    build: ./nginx
    ports: 
      - 80:80
#      - 443:443
    volumes: 
      - ./nginx/:/etc/nginx/conf.d/
      - ./www/:/usr/share/nginx/html

### My SQL #####################################
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
      
### PHPMYADMIN #####################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80
  