version: '3.1'
services:
  myapp:
    image: ${REGISTRY_HOST}/bbq-project/myapp:latest
  nginx:
    image: nginx:1.17.8-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./www/:/usr/share/nginx/html
  