version: "3.1"
services:
  ### NGINX #####################################
  nginx:
    image: nginx
    ports:
      - 8088:80
    # - 443:443
    volumes:
      - ./nginx:/etc/nginx
    restart: always
    networks:
      - api-network

  ### My SQL #####################################
  mysql:
    image: mysql:5.7
    container_name: dev_mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: bbq
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    restart: always
    networks:
      - api-network

  ### ADONIS #####################################
  adonis:
    build: ./adonis
    image: adonis-app-prod:1.0
    networks:
      - api-network
    # links:
    #   - mysql

  ### PHPMYADMIN #####################################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

networks:
  api-network:
